[package]
name = "proset"
version = "0.2.0"
authors = ["Kai Lieth <dubokk15@gmail.com>"]
edition = "2018"

[dependencies]
rand = "*"
rocket = { path = "../../SergioBenitez/Rocket/core/lib" }
rocket_contrib = { path = "../../SergioBenitez/Rocket/contrib/lib" }
serde = "*"
